language: node_js
node_js:
- '6'
env:
  global:
  - secure: hFvo2Dv08a3vx/91c/Xc/T4bZb7ibOJlNpwRJz4A6DnUoyhdklPaDDhv4R7W1mFWiTM1JxGIGV/st3amGkOzDZMEYHSFMRsQk/FLEryquDYYZhvadjFZbzsaL6lNYZB5KShY4TAzHBh3cBLhR7q30UvOD8WZHi3X8VcbPqm8kMrfVMuqp13BaIikFqFl2yD1RcKTfSXclYnvcoEznRNo6c0A5/S48TvXYMgfE0vTulDcab0NkT/5WzyIimMb0mOMGWtP0DV0F/NUjypXJeBLD9SoA+W1pQoS2XTof3CZ5doGOR6tTDoo6PLwkrEo9bG9yD0oupepmSJzpjmZYKai6RBsFW3e/tKltx8PpqxKItuFOBXkcO8yIkT0NpF05JldF8FhL/cOK62VYs/buS4I0mp43zqSsDgHXoBkaXLupCWld62HVpoQa++RKwqO/DRrhQLzawXbeZrw5ISDq6t9scWbF+AJ/C5d/regtd5RATLbSlj4ACergN1MEzsZVurfsnZeqchzFIsDZQSBZOOmuG820WVUm+n60C9uCly8qAPHKHjdhtnZIa3BJLmVTfWKKdNQS+AWR3d5DFrF3y3Ix50uOMYJesbpUfXhgdFlMSpPTWMnNGH+bPu7U8OQMq1y3Nd0J6oPOIGg6OJn8kMmk9xufYCH/t7MrEzSvWbqPFY=
  - secure: 5UlL4u491WpQGmhCrz9++Qma3boZSxnKWvE4hImOlbT2iPLslbkLF3Re2cDBVLPqg3duvgXt8dUfGubBuBlgAhTqX5sGKxZGeamuJ1phJ4VGZycDSIeBUTTZJhUR+xHUYaESHoZ2G5nVgN7o2hg70U8zR+1MDmRsC8GAmVAwO9LhfFC7IAseV3hkgPH+iGjc/j1LoB4YmPflQHf8Ww1pamDzJF4llCFTic1Q7zMbckhprZI+pIgasyOxsfQr7JivA9+T/WO+J0jnaiLG9NbzE2vx+e+yo5t2gbu0CxYXhJor8L0M2RzyG1mh/Ta3/PWS6NDYcG9v0/WdUZbc+X4JokoOibwN0QYokcl4DPqUhk2XoOeSgppoj5rBGgPh3MXKu0Fjx8jDn+EtF07KfFjCYwBOy7rs94aGcjXWUJqGzkyrD7Fwc0qqMD8FC0zfuLAVmKz5E/5q1YG3bGNstxiNicw0GSOlKSsjCT5p6vyhOrQbMHgtfrVPvFzQTicZfdVbv8cCw0gUMqBGS/7qXikZNz70BJzfuQhY+bLJSmKOKfuHMoGoj4xa/n72xs939Ts3lGLTfWFUsX/LaCM1LWCQs55P+XGbThgX8F7EX4eLIAZsein/kCoyuQ8nmst8LouZrNVRvKBb0BbTtAfAw2Lo7FxQ313ccLao8SRyZAJpHWM=
before_install:
- openssl aes-256-cbc -K $encrypted_ed0cdc322443_key -iv $encrypted_ed0cdc322443_iv
  -in .deployscp.enc -out .deployscp -d
- chmod 600 .deployscp
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
addons:
  ssh_known_hosts: 212.47.241.242
