language: node_js
node_js:
- '6'
env:
  global:
  - secure: vWxzm1E+rc8YQuW8nGe4F7aQIvFTkrcgjg9hg8AkjjITgeqr0b4+fihss8bL7d/Tx55bnr4FwbNk8y9WtlyNhsNbPIN8op142IEM+OjAvyiz8sqeECSSB6xLsFwLlbR9SFUZt0SKJstbjYHHj1e5wJOoSAg59bPM4cV8olVv0+w3Ns45GH+UOfS8bJAOV8wkKfUMZV3YFOLWYkiZYg+NO9deGQ5qji/dQWBLrsIlZ8EFlCJcYDTAQ349iaJU5xW7k6j+ghYXnx/7eZp29jRXmyWR6O357KTTXDVx+LeOnf13QPxct9jgrbYi8BDt34zrE3Y7unQLEv75T26UyRGnmNytfWgNkKnEgPLB6KZIUkcIfNydq8Tle7X0WXJBeYDZKa2bv5sjVy+12erj1Z75cUw7SnDfMWv24Y9a7Ppgw9GqNdA5u2z9ck57Nzn6PpVekkfcT7NA0pQSrPMIeFEHK4cinze6GWylryLL/t7s/+PHk81Nb4hpHvvIrzj3SBE1EqaD9S1vGO1Y70ARqb6bWLsF7uVZZacHXXrlJssrHmBWBilsZsd6bZPJvChkLrTI6/wfmWjqE3tPbcIkUMeh7U5oFs87qEBjKANRtoRQu8OZkZTSXLwfgBATbYq9/eQQSkCYg/CTDHY1z2IWU+OR7YlNEv/q/9zQaAm8i+GNRKo=
  - secure: AWnZxYgawtxiRyd0MEBR/ft/CNKFZmLTvLq9NdRqh2XTDmYpl3N0NgIygZnB4LS+DhSTYVzhYZjPTorfMyLi074tmq5gsuWQsEswmQf2MZLFe6lJCpmzWxH+5YrSMHKVYS2eVHNy+PL1omqPPKEZj5lZ5WTzdrUTuemjPFY6pO5Vpnw/hhw5djBB88ai0BwgRFnaNQA7ktr3usKUukUKtw0TZDp7WT96Ew8ssdGGM1PQyAN+CiuaDFN+i0ksJKPKOJ79DWNJ7SXI+b4qZyIL1jqA+8B17fC26gQcWTqf1Tlk468eyK/p5RRv7HJ2T1YYN9FASGTb0jjlxu2omRh1nE9xMY+IlGGA8zbpjkXDCailIN/HwcPvwBgnUn3b5qN2raMaudfl50Bi50dgl73CQoavDqlunztamxOGapCRI2ITUEj882Be0wYxOEB/sWTy2hKGr2dPS53PB74DFwZsk9dlHM07TcwgXccgOtLOtjaHPyT74HWXandcsRuUJ75gyoMs94eRwy2SzhxFBnJevTecDe3hVYSNN1dKrFlU2zqUKQ5bNgMF5Exjh/90Ecq3eycYd+AKDm9uNevw6vwka7BAR5WSyEqG+bZxGnq3mQ0JhaLAeYk6c8Cgi5c2r5hXMt9pFMabcd/bLWZhPJRhe4c8sg0TlZe3xTt+oa4ieO0=
before_deploy:
  - npm run package
deploy:
  skip_cleanup: true
  provider: s3
  local_dir: target
  upload-dir: slackbot
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: travis-artefacts
  region: eu-west-1
  on:
    branch: master
